[package]
name = "realistic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = { version = "0.4.1", features = ["num-bigint"] }
num-bigint = "0.4.4"
