#!/usr/bin/env python3
"""Generate independent high-precision reference values for the pnorm/qnorm tests.

Oracle: mpmath -- a separate arbitrary-precision implementation (erf via Taylor/
asymptotic/continued fractions) wholly unrelated to Boehm's constructive reals.
We emit DIGITS fractional digits, TRUNCATED toward zero to match the test's
truncating renderer, frozen into src/real/normal_reference.rs which
`against_mpmath_references` compares against digit-for-digit.

Ported from the Swift constructive-calculator's Design/test-references/
gen_normal_refs.py; same cases and math, Rust output. Re-run after
`pip install --user mpmath`:  python3 tools/gen_normal_refs.py
A correct tree yields a no-op diff on src/real/normal_reference.rs.
"""
import os
import mpmath as mp

DIGITS = 1000
mp.mp.dps = DIGITS + 60


def trunc_str(x, n=DIGITS):
    sign = '-' if x < 0 else ''
    x = abs(x)
    scaled = int(mp.floor(x * mp.mpf(10) ** n))   # exact at this dps
    s = str(scaled)
    if len(s) <= n:
        s = '0' * (n - len(s) + 1) + s
    return sign + s[:-n] + '.' + s[-n:]


def qnorm(p):
    return mp.sqrt(2) * mp.erfinv(2 * p - 1)


# (numerator, denominator) -- inputs as exact rationals.
pnorm_cases = [(10, 1), (-10, 1), (99, 10), (-99, 10), (9, 1), (-9, 1), (5, 1),
               (-5, 1), (25, 10), (-25, 10), (1, 1), (-1, 1), (1, 2)]
qnorm_cases = [(1, 2), (975, 1000), (999, 1000),
               (1, 10), (1, 100), (1, 10**4), (1, 10**8), (1, 10**16),
               (1, 10**23), (8, 10**24),
               (9, 10), (99, 100), (10**4 - 1, 10**4), (10**16 - 1, 10**16),
               (10**23 - 1, 10**23)]

rows = []
for n, d in pnorm_cases:
    rows.append(('pnorm', n, d, trunc_str(mp.ncdf(mp.mpf(n) / d))))
for n, d in qnorm_cases:
    rows.append(('qnorm', n, d, trunc_str(qnorm(mp.mpf(n) / mp.mpf(d)))))

out = [
    '// GENERATED by tools/gen_normal_refs.py -- do not edit by hand.',
    '// Independent reference values from mpmath (%d fractional digits, truncated' % DIGITS,
    '// toward zero). mpmath is an arbitrary-precision library wholly independent of',
    "// Boehm's constructive reals, so this is a genuine external oracle for pnorm/qnorm.",
    '//',
    '// (kind, numerator, denominator, value truncated to %d fractional digits)' % DIGITS,
    '#[cfg(test)]',
    'pub(super) const CASES: &[(&str, &str, &str, &str)] = &[',
]
for kind, n, d, val in rows:
    out.append('    ("%s", "%d", "%d", "%s"),' % (kind, n, d, val))
out += ['];', '']

_dst = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                    '..', 'src', 'real', 'normal_reference.rs')
with open(_dst, 'w') as f:
    f.write('\n'.join(out))
print("wrote %d cases, %d digits each, to %s" % (len(rows), DIGITS, os.path.normpath(_dst)))
